// CHECKSTYLE:OFF
package com.baidu.share.config;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * 分享配置的数据结构
 * Entity mapped to table share_config_table.
 *
 * @author zhangyuchao, fanjihuan
 */
public class ShareConfigData {

    private Long id;
    /** 标识分享配置是否统一：若为all，则所有平台读取相同的配置信息，否则读取微信、QQ、微博 */
    private String media;
    /** 分享的方式：image、url、default */
    private String form;
    /** 分享入口：包含详情页、幸运抽奖、洗白白 */
    private String entry;
    /** 分享的标题 */
    private String title;
    /** 分享的内容 */
    private String content;
    /** 分享的图标 */
    private String icon;
    /** 分享的大图 */
    private String image;
    /** 分享的链接 */
    private String link;

    // KEEP FIELDS - put your custom fields here
    /** 分享入口：详情页分享KEY */
    public static final String SHARE_APP = "appdetail";
    /** 分享入口：幸运抽奖分享KEY */
    public static final String SHARE_LOTTERY = "lottery";
    /** 分享入口：洗白白分享KEY */
    public static final String SHARE_WASH = "wash";
    // KEEP FIELDS END

    public ShareConfigData() {
    }

    public ShareConfigData(Long id) {
        this.id = id;
    }

    public ShareConfigData(Long id, String media, String form, String entry,
                           String title, String content, String icon, String image, String link) {
        this.id = id;
        this.media = media;
        this.form = form;
        this.entry = entry;
        this.title = title;
        this.content = content;
        this.icon = icon;
        this.image = image;
        this.link = link;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMedia() {
        return media;
    }

    public void setMedia(String media) {
        this.media = media;
    }

    public String getForm() {
        return form;
    }

    public void setForm(String form) {
        this.form = form;
    }

    public String getEntry() {
        return entry;
    }

    public void setEntry(String entry) {
        this.entry = entry;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getLink() {
        return link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("[media=").append(media).append(",form=").append(form).append(",entry=")
                .append(entry).append(" ,title=").append(title).append(",content=").append(content).append(",icon=")
                .append(icon).append(" ,image=").append(image).append(" ,link=").append(link).append("]");
        return sb.toString();
    }
    // KEEP METHODS END

}
